nmHoistingLimits: workspaces
nodeLinker: node-modules
pnpEnableEsmLoader: true

packageExtensions:
  'babel-plugin-transform-flow-enums@*':
    peerDependencies:
      '@babel/core': '*'
  'babel-preset-expo@*':
    peerDependencies:
      '@babel/core': '*'
  'react-native@*':
    peerDependencies:
      '@babel/core': '*'
  'expo-linking@*':
    peerDependencies:
      'expo': '*'
  'eslint-config-expo@*':
    peerDependencies:
      'typescript': '*'
  'eslint-plugin-expo@*':
    peerDependencies:
      'typescript': '*'
  'nativewind@*':
    peerDependencies:
      'react': '*'
      'react-native': '*'
      'react-native-reanimated': '*'
  '@expo/mcp-tunnel@*':
    peerDependencies:
      '@modelcontextprotocol/sdk': '*'
